# Generated by Django 3.1.3 on 2020-12-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='catname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
